# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'xdag-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for xdag-ios
  pod 'paper-onboarding', :git => 'https://github.com/Ramotion/paper-onboarding.git'
  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Zip', '~> 1.1'

  target 'xdag-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'xdag-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '4.0'
          end
      end
  end
end
